---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-comparison-test
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectl-comparison-test-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-comparison-test-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubectl-comparison-test-secrets
subjects:
- kind: ServiceAccount
  name: kubectl-comparison-test
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-comparison-test
  labels:
    app: kubectl-comparison-test
spec:
  serviceAccountName: kubectl-comparison-test
  containers:
  - name: test-client
    image: bitnami/kubectl:latest
    command:
    - /bin/sh
    - -c
    - |
      echo "=== Direct Kubernetes Secret (identity namespace) ==="
      echo "Getting secret directly from identity namespace:"
      echo ""
      ORIGINAL=$(kubectl get secret identity-token-creation-private-key -n identity -o jsonpath='{.data.test\.pem}' | base64 -d)
      echo "$ORIGINAL"
      echo ""
      echo "=== Secrets Router Response ==="
      echo "Getting secret via secrets-router.default.svc.cluster.local:"
      echo ""
      ROUTER_RESPONSE=$(curl -s secrets-router.default.svc.cluster.local:8080/secrets/identity-token-creation-private-key/test.pem?namespace=identity)
      echo "$ROUTER_RESPONSE"
      echo ""
      
      # Extract the value field using jq
      SECRET_VALUE=$(echo "$ROUTER_RESPONSE" | jq -r '.value')
      echo "=== Extracted PEM Value (using jq) ==="
      echo "$SECRET_VALUE"
      echo ""
      
      echo "=== Comparison ==="
      echo "Comparing direct kubectl access vs secrets-router response:"
      if [ "$ORIGINAL" = "$SECRET_VALUE" ]; then
        echo "✅ SUCCESS: PEM content is IDENTICAL"
        echo "✅ Content length matches: $(echo "$ORIGINAL" | wc -c) bytes"
        echo "✅ Line count matches: $(echo "$ORIGINAL" | wc -l) lines"
        echo "✅ First line: $(echo "$ORIGINAL" | head -1)"
        echo "✅ Last line: $(echo "$ORIGINAL" | tail -1)"
        echo ""
        echo "🎉 SECRET ROUTER RETURNS UNADULTERATED SECRET DATA!"
        echo "🎉 Applications receive exact decoded secret value!"
        echo "🎉 Secrets-router handles newline decoding automatically!"
      else
        echo "❌ FAILURE: PEM content differs"
        echo "Original length: $(echo "$ORIGINAL" | wc -c) bytes"
        echo "Router length: $(echo "$SECRET_VALUE" | wc -c) bytes"
        echo "Original lines: $(echo "$ORIGINAL" | wc -l)"
        echo "Router lines: $(echo "$SECRET_VALUE" | wc -l)"
        echo ""
        echo "First 5 lines of original:"
        echo "$ORIGINAL" | head -5
        echo ""
        echo "First 5 lines from router:"
        echo "$SECRET_VALUE" | head -5
      fi
      
      sleep 3600
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  restartPolicy: Never
