apiVersion: v1
kind: Pod
metadata:
  name: kubectl-comparison-test
  labels:
    app: kubectl-comparison-test
spec:
  containers:
  - name: test-client
    image: bitnami/kubectl:latest
    command:
    - /bin/sh
    - -c
    - |
      echo "=== Direct Kubernetes Secret ==="
      echo "Getting secret directly from Kubernetes:"
      echo ""
      ORIGINAL=$(kubectl get secret test-secret -o jsonpath='{.data.test\.pem}' | base64 -d)
      echo "$ORIGINAL"
      echo ""
      echo "=== Secrets Router Response ==="
      echo "Getting secret via secrets-router:"
      echo ""
      ROUTER_RESPONSE=$(curl -s secrets-router:8080/secrets/test-secret/test.pem)
      echo "$ROUTER_RESPONSE"
      echo ""
      echo "=== Extracted PEM from secrets-router ==="
      SECRET_VALUE=$(echo "$ROUTER_RESPONSE" | sed 's/.*"value":"\([^"]*\)".*/\1/' | sed 's/\\n/\n/g')
      echo "$SECRET_VALUE"
      echo ""
      echo "=== Exacting Comparison ==="
      echo "Comparing byte-by-byte:"
      if [ "$ORIGINAL" = "$SECRET_VALUE" ]; then
        echo "✅ SUCCESS: PEM content is IDENTICAL"
        echo "✅ Content length matches: $(echo "$ORIGINAL" | wc -c) bytes"
        echo "✅ Line count matches: $(echo "$ORIGINAL" | wc -l) lines"
        echo "✅ First line: $(echo "$ORIGINAL" | head -1)"
        echo "✅ Last line: $(echo "$ORIGINAL" | tail -1)"
        echo ""
        echo "🎉 CERTIFICATE/KEY FILES WILL WORK CORRECTLY!"
        echo "🎉 No modification or corruption detected!"
      else
        echo "❌ FAILURE: PEM content differs"
        echo "Original length: $(echo "$ORIGINAL" | wc -c) bytes"
        echo "Router length: $(echo "$SECRET_VALUE" | wc -c) bytes"
        echo "Original lines: $(echo "$ORIGINAL" | wc -l)"
        echo "Router lines: $(echo "$SECRET_VALUE" | wc -l)"
        echo ""
        echo "First 5 lines of original:"
        echo "$ORIGINAL" | head -5
        echo ""
        echo "First 5 lines from router:"
        echo "$SECRET_VALUE" | head -5
      fi
      
      sleep 3600
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  restartPolicy: Never
