apiVersion: v1
kind: Pod
metadata:
  name: secret-display-service
  labels:
    app: secret-display-service
spec:
  containers:
  - name: secret-display
    image: python:3.9-slim
    command: ["sh", "-c", "apt-get update && apt-get install -y curl && pip install requests && python3 -c \"
import requests
import sys
import json
import base64

try:
    # Test health endpoint
    health_response = requests.get('http://secrets-router:8080/healthz')
    print('=== Secrets Router Health ===')
    print(json.dumps(health_response.json(), indent=2))
    print()
    
    # Get secret value
    secret_response = requests.get('http://secrets-router:8080/secrets/test-secret/test.pem')
    secret_data = secret_response.json()
    
    print('=== Secret Retrieved ===')
    print(f'Secret Name: {secret_data[\"secret_name\"]}')
    print(f'Secret Key: {secret_data[\"secret_key\"]}')
    print(f'Backend: {secret_data[\"backend\"]}')
    print()
    
    # Display first and last few lines of the PEM content
    pem_content = secret_data['value']
    lines = pem_content.split('\\n')
    print('=== PEM Content Preview ===')
    print('First 5 lines:')
    for i, line in enumerate(lines[:5]):
        print(f'{i+1}: {line}')
    
    if len(lines) > 10:
        print('...')
        print('Last 5 lines:')
        for i, line in enumerate(lines[-5:], len(lines)-4):
            print(f'{i}: {line}')
    elif len(lines) <= 10:
        for i, line in enumerate(lines[len(lines)-5:]):
            print(f'{i+1}: {line}')
    
    print()
    print(f'Total lines: {len(lines)}')
    print('=== Secret Retrieval Successful ===')
    
except Exception as e:
    print(f'Error retrieving secret: {e}')
    sys.exit(1)
\""]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  restartPolicy: Never
