apiVersion: v1
kind: Pod
metadata:
  name: simple-secret-test
  labels:
    app: simple-secret-test
spec:
  containers:
  - name: test-client
    image: curlimages/curl:latest
    command:
    - /bin/sh
    - -c
    - |
      echo "=== Fetching secret from secrets-router ==="
      echo "Request: GET /secrets/test-secret/test.pem"
      echo ""
      echo "Raw response:"
      curl -s secrets-router:8080/secrets/test-secret/test.pem
      echo ""
      echo ""
      echo "=== Test Complete ==="
      sleep 3600
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  restartPolicy: Never
