apiVersion: v1
kind: Pod
metadata:
  name: cross-namespace-manual-test
  namespace: test-2-clients
spec:
  restartPolicy: Never
  containers:
    - name: test-client
      image: curlimages/curl
      command:
        - /bin/sh
        - -c
        - |
          echo "Testing cross-namespace access to secrets-router in test-1 namespace..."
          echo "URL: http://secrets-router.test-1.svc.cluster.local:8080/healthz"
          echo ""
          
          echo "Testing health check:"
          curl -v http://secrets-router.test-1.svc.cluster.local:8080/healthz
          echo ""
          
          echo "Testing secret retrieval:"
          curl -s http://secrets-router.test-1.svc.cluster.local:8080/secrets/sample-secret/password | jq
          echo ""
          
          echo "Testing with wrong namespace (should fail):"
          curl -s http://secrets-router.test-2-clients.svc.cluster.local:8080/healthz || echo "Failed as expected"
  terminationGracePeriodSeconds: 0
