#!/bin/bash

# K8s-Secrets-Broker Helm Installation Script
# Automated deployment of the umbrella Helm chart with configurable options

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Default configuration
RELEASE_NAME="secrets-broker"
NAMESPACE="demo"
CHART_PATH="$PROJECT_ROOT/charts/umbrella"
VALUES_FILE=""
CREATE_NAMESPACE=false
DRY_RUN=false
WAIT=false
TIMEOUT=300
AWS_SECRETS_MANAGER=false
AWS_REGION="us-east-1"
AWS_MULTI_VALUE_SECRETS=false

# Parse command line arguments
function show_help() {
    cat << EOF
Usage: $0 [OPTIONS]

Deploy the K8s-Secrets-Broker umbrella Helm chart with configurable options.

OPTIONS:
    -r, --release NAME       Helm release name (default: secrets-broker)
    -n, --namespace NAME     Kubernetes namespace (default: dapr-control-plane)
    -f, --values FILE        Path to values file
    -c, --create-namespace   Create namespace if it doesn't exist (default: true)
    --no-create-namespace    Don't create namespace
    --dry-run              Render templates without installing
    --wait                 Wait for deployment to complete
    --timeout SECONDS      Timeout for --wait (default: 300)
    --aws-secrets          Enable AWS Secrets Manager
    --aws-region REGION    AWS region for secrets manager (default: us-east-1)
    --aws-multi-value      Enable multiple key-value pairs per secret
    --local-images         Use local images (pullPolicy: Never)
    -h, --help             Show this help message

EXAMPLES:
    # Basic installation
    $0

    # Installation with custom values
    $0 -f my-values.yaml -n my-namespace

    # AWS Secrets Manager configuration
    $0 --aws-secrets --aws-region us-west-2 --aws-multi-value

    # Dry run with custom namespace
    $0 --dry-run -n test-namespace

    # Local development setup
    $0 --local-images -f testing/override.yaml

EOF
}

while [[ $# -gt 0 ]]; do
    case $1 in
        -r|--release)
            RELEASE_NAME="$2"
            shift 2
            ;;
        -n|--namespace)
            NAMESPACE="$2"
            shift 2
            ;;
        -f|--values)
            VALUES_FILE="$2"
            shift 2
            ;;
        -c|--create-namespace)
            CREATE_NAMESPACE=true
            shift
            ;;
        --no-create-namespace)
            CREATE_NAMESPACE=false
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --wait)
            WAIT=true
            shift
            ;;
        --timeout)
            TIMEOUT="$2"
            shift 2
            ;;
        --aws-secrets)
            AWS_SECRETS_MANAGER=true
            shift
            ;;
        --aws-region)
            AWS_REGION="$2"
            shift 2
            ;;
        --aws-multi-value)
            AWS_MULTI_VALUE_SECRETS=true
            shift
            ;;
        --local-images)
            LOCAL_IMAGES=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
function log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

function log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

function log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

function log_header() {
    echo -e "${BLUE}=== $1 ===${NC}"
}

function check_command() {
    if ! command -v "$1" &> /dev/null; then
        log_error "$1 is required but not installed"
        exit 1
    fi
}

function check_kubernetes() {
    if ! kubectl cluster-info &> /dev/null; then
        log_error "Kubernetes cluster is not accessible"
        exit 1
    fi
}

function check_helm_chart() {
    if [[ ! -d "$CHART_PATH" ]]; then
        log_error "Helm chart not found at $CHART_PATH"
        exit 1
    fi
}

function generate_temp_values() {
    local temp_values=$(mktemp)
    trap "rm -f $temp_values" EXIT
    
    cat > "$temp_values" << EOF
# Generated by helm-install.sh
secrets-router:
  secretStores:
    aws:
      enabled: ${AWS_SECRETS_MANAGER}
      region: "${AWS_REGION}"
      multipleKeyValuesPerSecret: ${AWS_MULTI_VALUE_SECRETS}
EOF

    if [[ "${LOCAL_IMAGES:-false}" == "true" ]]; then
        cat >> "$temp_values" << EOF
  image:
    pullPolicy: Never
EOF
    fi
    
    echo "$temp_values"
}

echo "🚀 K8s-Secrets-Broker Helm Installation"
log_header "Configuration"
echo "Release Name: $RELEASE_NAME"
echo "Namespace: $NAMESPACE"
echo "Chart Path: $CHART_PATH"
if [[ -n "$VALUES_FILE" ]]; then
    echo "Values File: $VALUES_FILE"
fi
echo "AWS Secrets Manager: $AWS_SECRETS_MANAGER"
if [[ "$AWS_SECRETS_MANAGER" == "true" ]]; then
    echo "AWS Region: $AWS_REGION"
    echo "AWS Multi-Value Secrets: $AWS_MULTI_VALUE_SECRETS"
fi
echo "Dry Run: $DRY_RUN"
echo "Wait: $WAIT"
echo "=================================="

# 1. Prerequisites check
log_header "Prerequisites"
log_info "Checking required tools..."
check_command "kubectl"
check_command "helm"

log_info "Checking Kubernetes cluster..."
check_kubernetes

log_info "Checking Helm chart..."
check_helm_chart

# 2. Check namespace
log_header "Namespace Check"
if kubectl get namespace "$NAMESPACE" &> /dev/null; then
    log_info "Namespace '$NAMESPACE' already exists"
else
    if [[ "$CREATE_NAMESPACE" == "true" ]]; then
        log_info "Creating namespace '$NAMESPACE'..."
        kubectl create namespace "$NAMESPACE"
        log_info "✅ Namespace created successfully"
    else
        log_warn "Namespace '$NAMESPACE' does not exist and --no-create-namespace was specified"
        log_warn "Please create the namespace manually: kubectl create namespace $NAMESPACE"
        exit 1
    fi
fi

# 3. Build Helm command
log_header "Build Command"
HELM_CMD="helm upgrade --install $RELEASE_NAME $CHART_PATH"

# Add namespace
HELM_CMD="$HELM_CMD --namespace $NAMESPACE"

# Add create namespace flag if requested
if [[ "$CREATE_NAMESPACE" == "true" ]]; then
    HELM_CMD="$HELM_CMD --create-namespace"
fi

# Add dry run flag if requested
if [[ "$DRY_RUN" == "true" ]]; then
    HELM_CMD="$HELM_CMD --dry-run"
fi

# Add wait flag if requested
if [[ "$WAIT" == "true" ]]; then
    HELM_CMD="$HELM_CMD --wait --timeout ${TIMEOUT}s"
fi

# Collect values files
VALUES_FILES=()

# Add user-provided values file
if [[ -n "$VALUES_FILE" && -f "$VALUES_FILE" ]]; then
    VALUES_FILES+=("$VALUES_FILE")
    log_info "Including values file: $VALUES_FILE"
elif [[ -n "$VALUES_FILE" ]]; then
    log_warn "Values file '$VALUES_FILE' not found, skipping"
fi

# Add/temporary values for AWS/local images configuration
if [[ "$AWS_SECRETS_MANAGER" == "true" || "${LOCAL_IMAGES:-false}" == "true" ]]; then
    TEMP_VALUES=$(generate_temp_values)
    VALUES_FILES+=("$TEMP_VALUES")
    log_info "Including temporary values for AWS/local configuration"
fi

# Add values files to command
for values_file in "${VALUES_FILES[@]}"; do
    HELM_CMD="$HELM_CMD -f $values_file"
done

# 4. Execute Helm command
log_header "Deployment"
log_info "Running Helm command:"
log_info "$HELM_CMD"
echo ""

if eval "$HELM_CMD"; then
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "✅ Dry run completed successfully"
        log_info "Templates rendered without any errors"
    else
        log_info "✅ Helm installation completed successfully"
        
        # Show deployment status
        log_header "Deployment Status"
        log_info "Checking pods in namespace '$NAMESPACE'..."
        kubectl get pods -n "$NAMESPACE" -l app.kubernetes.io/part-of=secrets-broker || true
        
        log_info "Checking services in namespace '$NAMESPACE'..."
        kubectl get services -n "$NAMESPACE" -l app.kubernetes.io/part-of=secrets-broker || true
        
        if [[ "$WAIT" == "false" ]]; then
            echo ""
            log_info "To check deployment status:"
            echo "  kubectl get pods -n $NAMESPACE"
            echo "  kubectl get services -n $NAMESPACE"
            echo ""
            log_info "To check logs:"
            echo "  kubectl logs -n $NAMESPACE -l app.kubernetes.io/name=secrets-router"
        fi
    fi
else
    log_error "❌ Helm installation failed"
    exit 1
fi

# 5. Show next steps
if [[ "$DRY_RUN" == "false" ]]; then
    log_header "Next Steps"
    echo "🎉 Secrets-broker has been deployed successfully!"
    echo ""
    echo "To test the deployment:"
    echo " 1. Check that all pods are running:"
    echo "     kubectl get pods -n $NAMESPACE"
    echo ""
    echo "  2. Test the secrets-router service:"
    echo "     kubectl exec -n $NAMESPACE -c python-client deployment/\${RELEASE_NAME}-sample-service-python --"
    echo "       curl \"http://secrets-router:8080/healthz\""
    echo ""
    echo "  3. Test secret access (if secrets are configured):"
    echo "     kubectl exec -n $NAMESPACE -c python-client deployment/\${RELEASE_NAME}-sample-service-python --"
    echo "       curl \"http://secrets-router:8080/secrets/your-secret/your-key?namespace=$NAMESPACE\""
    echo ""
    echo "To uninstall:"
    echo "  helm uninstall $RELEASE_NAME --namespace $NAMESPACE"
fi

echo ""
log_info "🎉 Script completed successfully!"
