apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aws-secrets-manager
  namespace: default
spec:
  type: secretstores.aws.secretsmanager
  version: v1
  metadata:
  - name: region
    value: "us-east-1"
  # Alternative: Use IRSA (IAM Role for ServiceAccount)
  # Remove accessKey and secretKey if using IRSA
  auth:
    secretStore: kubernetes

