{{- if .Values.client.python.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "sample-service.fullname" . }}-python
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: python-client
spec:
  restartPolicy: {{ .Values.restartPolicy }}
  containers:
    - name: python-client
      image: "{{ .Values.client.python.image }}:{{ .Values.client.python.tag | default "latest" }}"
      imagePullPolicy: {{ .Values.client.python.pullPolicy }}
      env:
        - name: SECRETS_ROUTER_URL
          value: {{ .Values.secretsRouter.url | quote }}
        - name: NAMESPACE
          value: {{ .Values.secretsRouter.namespace | quote }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
  terminationGracePeriodSeconds: 0
{{- end }}
