{{- if .Values.client.python.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "sample-service.fullname" . }}-python
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: python-client
spec:
  restartPolicy: {{ .Values.restartPolicy }}
  containers:
    - name: python-client
      image: "{{ .Values.client.python.image }}:{{ .Values.client.python.tag | default "latest" }}"
      imagePullPolicy: {{ .Values.client.python.pullPolicy }}
      env:
        - name: SECRETS_ROUTER_URL
          value: {{ .Values.secretsRouter.url | quote }}
        - name: TEST_NAMESPACE
          value: {{ .Values.secretsRouter.namespace | quote }}
        {{- if .Values.client.python.secrets }}
        {{- $availableSecrets := list }}
        {{- range $secretKey, $secretPath := .Values.client.python.secrets }}
        {{- $availableSecrets = append $availableSecrets $secretKey }}
        - name: SECRET_{{ $secretKey | upper | replace "-" "_" }}
          value: {{ $secretPath | quote }}
        {{- end }}
        - name: AVAILABLE_SECRETS
          value: {{ join "," $availableSecrets | quote }}
        {{- else }}
        - name: TEST_SECRET_NAME
          value: {{ .Values.testSecret.name | quote }}
        - name: TEST_SECRET_KEY
          value: "password"
        {{- end }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
  terminationGracePeriodSeconds: 0
{{- end }}
